name: conversa_ai
description: "ConversaAI - Learn English through natural conversations"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  chat_bubbles: ^1.6.0
  
  # State Management
  provider: ^6.1.1
  
  # Animations
  lottie: ^3.0.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0
  
  # Audio for recording and playback
  record: ^6.1.0
  audioplayers: ^6.5.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  flutter_tts: ^4.1.0
  speech_to_text: ^7.0.0
  
  # HTTP & API (for future backend integration)
  http: ^1.1.2
  dio: ^5.4.0
  
  # Storage (for future backend integration)
  shared_preferences: ^2.2.2
  
  # Utils
  flutter_svg: ^2.0.9
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  
  # App icon generation
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# App icon configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/LOGO.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/LOGO.png"
    background_color: "#ffffff"
    theme_color: "#007AFF"
  windows:
    generate: true
    image_path: "assets/images/LOGO.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/LOGO.png"
  linux:
    generate: true
    image_path: "assets/images/LOGO.png"
